"""
packager.py
===========
Creates the contribution folder and all required files inside the JARVIS repo.
"""

from __future__ import annotations

import json
import os
import shutil
import zipfile
from pathlib import Path
from typing import Dict, List, Optional

from jarvis_leaderboard_uploader.logger import JarvisLogger
from jarvis_leaderboard_uploader.validator import BenchmarkName


class Packager:
    def __init__(self, repo_path: str | Path, logger: Optional[JarvisLogger] = None):
        self.repo_path = Path(repo_path)
        self.contributions_dir = self.repo_path / "jarvis_leaderboard" / "contributions"
        self.logger = logger or JarvisLogger()

        if not self.repo_path.exists():
            raise FileNotFoundError(
                f"Repository path not found: {self.repo_path}\n"
                "Make sure you have cloned the jarvis_leaderboard repo and the path is correct."
            )
        if not self.contributions_dir.exists():
            raise FileNotFoundError(
                f"Contributions directory not found: {self.contributions_dir}\n"
                "Expected path: jarvis_leaderboard/contributions/ inside the repo.\n"
                "Check that --repo_path points to the root of the cloned repository."
            )

    def create_contribution(
        self,
        *,
        contribution_name: str,
        benchmark: BenchmarkName,
        csv_path: str | Path,
        metadata: Dict,
        run_script: Optional[str | Path] = None,
        run_py: Optional[str | Path] = None,
        dockerfile: Optional[str | Path] = None,
        overwrite: bool = False,
    ) -> Path:
        safe_name = _sanitize_name(contribution_name)
        dest = self.contributions_dir / safe_name

        self.logger.step(f"Creating contribution folder: {dest}")

        if dest.exists():
            if overwrite:
                self.logger.warning(f"Folder '{dest}' already exists — overwriting.")
                shutil.rmtree(dest)
            else:
                raise FileExistsError(
                    f"Contribution folder already exists: {dest}\n"
                    "Use overwrite=True (or --overwrite on the CLI) to replace it."
                )

        dest.mkdir(parents=True)
        self.logger.success(f"Folder created: {dest}")

        self._write_csv_zip(csv_path=Path(csv_path), benchmark=benchmark, dest_dir=dest)
        self._write_metadata(metadata, dest)

        if run_script and Path(run_script).exists():
            shutil.copy(run_script, dest / "run.sh")
            self.logger.success(f"Copied run.sh from {run_script}")
        else:
            self._write_run_sh_template(benchmark, dest)

        if run_py and Path(run_py).exists():
            shutil.copy(run_py, dest / "run.py")
            self.logger.success(f"Copied run.py from {run_py}")
        if dockerfile and Path(dockerfile).exists():
            shutil.copy(dockerfile, dest / "Dockerfile")
            self.logger.success(f"Copied Dockerfile from {dockerfile}")

        self.logger.success(
            f"Contribution folder ready at: {dest}\n"
            f"  Files: {sorted(p.name for p in dest.iterdir())}"
        )
        return dest

    def _write_csv_zip(self, csv_path: Path, benchmark: BenchmarkName, dest_dir: Path) -> Path:
        zip_dest = dest_dir / benchmark.zip_filename
        self.logger.step(f"Creating {benchmark.zip_filename}")
        if not csv_path.exists():
            raise FileNotFoundError(
                f"Predictions CSV not found: {csv_path}\n"
                "Check that the path passed to csv_path is correct."
            )
        with zipfile.ZipFile(zip_dest, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.write(csv_path, arcname=benchmark.csv_filename)
        self.logger.success(f"Created zip: {zip_dest}")
        return zip_dest

    def _write_metadata(self, metadata: Dict, dest_dir: Path) -> None:
        self.logger.step("Writing metadata.json")
        meta_path = dest_dir / "metadata.json"
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)
        self.logger.success(f"metadata.json written: {meta_path}")

    def _write_run_sh_template(self, benchmark: BenchmarkName, dest_dir: Path) -> None:
        self.logger.step("Generating run.sh template")
        script = dest_dir / "run.sh"
        content = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by jarvis_leaderboard_uploader\n"
            "# Edit this file to reproduce your benchmark results.\n"
            "#\n"
            f"# Benchmark: {benchmark.raw}\n"
            f"# Method   : {benchmark.method}\n"
            f"# Property : {benchmark.property_name}\n"
            f"# Dataset  : {benchmark.dataset}\n"
            f"# Split    : {benchmark.split}\n"
            "#\n"
            "# Example steps (adapt as needed):\n"
            "# pip install my_model_package\n"
            "# python run.py\n"
        )
        script.write_text(content)
        self.logger.success(f"Template run.sh written: {script}")
        self.logger.warning(
            "A run.sh template was generated — please edit it before submitting the pull request."
        )

    def list_existing_contributions(self) -> List[str]:
        if not self.contributions_dir.exists():
            return []
        return sorted(
            p.name for p in self.contributions_dir.iterdir()
            if p.is_dir() and not p.name.startswith(".")
        )

    def get_contribution_path(self, name: str) -> Path:
        return self.contributions_dir / name


def _sanitize_name(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_." else "_" for c in name)